# generated by datamodel-codegen:
#   filename:  credentials-service-api-v2.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class OAuth2TokenRevocationRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    token: Annotated[
        str,
        Field(description="The token that has to be removed.", examples=["papi-dcec6d81-8c0f-47f0-9dd8-4e59755f041a"]),
    ]


class OAuth2TokenRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    client_id: Annotated[
        str,
        Field(description="The client's unique identifier.", examples=["papi-dcec6d81-8c0f-47f0-9dd8-4e59755f041a"]),
    ]
    client_secret: Annotated[
        str,
        Field(
            description="The client's secret key.",
            examples=["papi-FTcGcxmX_dmH2AkBARp2ms8VDZvQtJQJ0j0sdIJRrRrXdlTytZOr5QLY1fLYGEeWRzmb7e5Cqd7GIdjnMj0Z7w"],
        ),
    ]
    grant_type: Annotated[
        str,
        Field(
            description="The grant type being used. At the moment, only `client_credentials` grant type is supported.",
            examples=["client_credentials"],
        ),
    ]
    scope: Annotated[
        str | None,
        Field(
            description='Requested scopes for the issued token. Space-delimited list; order doesn\'t matter. If no scope is provided, all scopes available to the client will be assigned.\n\nExample: "documents:read documents:write"\n',
            examples=["documents:read documents:write"],
        ),
    ] = None


class OAuth2Token(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    access_token: Annotated[
        str | None,
        Field(
            description="The access token from the grant type flow.",
            examples=["papi-OUYVj9QdAyL8F-Naa0PB7X2CZVb0uHDTYvW_FoX1o3lJBgvbcJ_ctlJ8nH4FDi6QWl5BHlzj-CheybZaxVRq0g"],
        ),
    ] = None
    refresh_token: Annotated[
        str | None,
        Field(
            description="Token to be used for refreshing the access token. Can be omitted for some grant types.",
            examples=["papi-OUYVj9QdAyL8F-Naa0PB7X2CZVb0uHDTYvW_FoX1o3lJBgvbcJ_ctlJ8nH4FDi6QWl5BHlzj-CheybZaxVRq0g"],
        ),
    ] = None
    token_type: Annotated[str | None, Field(description="The type of the access token.", examples=["Bearer"])] = None
    expires_in: Annotated[
        int | None,
        Field(
            description="The remaining lifetime of the access token, expressed in seconds. The default value is 1 day.",
            examples=[86400],
        ),
    ] = None
    scope: Annotated[
        str | None,
        Field(
            description="Space delimited array of scopes assigned to the granted token. Order doesn't matter.",
            examples=["documents:read documents:write"],
        ),
    ] = None


class OAuth2TokenErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    error: Annotated[
        str | None, Field(description="Error type that happened, see OAuth2.0 specs.", examples=["unauthorized_client"])
    ] = None
    error_description: Annotated[
        str | None,
        Field(
            description="The description of the error.",
            examples=[
                "The credentials were not correct. Make sure you are providing the right client_id and client_secret."
            ],
        ),
    ] = None
    error_uri: Annotated[
        str | None,
        Field(
            description="A URI identifying a human-readable web page with additional information about the error.",
            examples=["https://developer.personio.de/reference/errors#credentials.invalid_grant"],
        ),
    ] = None
    timestamp: Annotated[
        AwareDatetime | None,
        Field(
            description="The timestamp when the response was generated on the server.",
            examples=["2023-03-01T14:07:17Z"],
        ),
    ] = None
    trace_id: Annotated[
        str | None,
        Field(
            description="A unique trace ID used for tracking the request inside Personio system.",
            examples=["baaaaaad-c0de-fade-baad-c000000000de"],
        ),
    ] = None
    meta: Annotated[
        dict[str, Any] | None,
        Field(
            description="Object containing meta information about the error. Can be empty.",
            examples=[{"grant_type": "let_me_in"}],
        ),
    ] = None


class V1AuthTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    client_id: Annotated[str, Field(description="API Client id")]
    client_secret: Annotated[str, Field(description="API Client secret")]


class V1AuthenticationTokenResponseDataData(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    token: str


class V1AuthenticationTokenResponseData(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    data: V1AuthenticationTokenResponseDataData | None = None


class V1AuthenticationTokenResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    success: bool | None = None
    data: V1AuthenticationTokenResponseData | None = None
