# generated by datamodel-codegen:
#   filename:  employment-contract-v2.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class OrgUnit(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    type: Annotated[str | None, Field(description="The type of the Org Unit, e.g. team or department.")] = None
    id: Annotated[str | None, Field(description="The Internal ID of the Org Unit.")] = None


class CostCenter(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `cost_center`.")] = None
    weight: Annotated[float | None, Field(description="The weight of the `cost_center`.")] = None


class EmploymentPosition(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    title: Annotated[str | None, Field(description="The title of the `position`.")] = None


class EmploymentSupervisor(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the supervisor.")] = None


class EmploymentOffice(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `office`.")] = None


class EmploymentPerson(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `person`.")] = None


class EmploymentLegalEntity(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the employment legal entity.")] = None


class EmploymentJob(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `job`.")] = None


class EmploymentSubCompany(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the employment sub-company.")] = None


class Termination(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    termination_date: Annotated[date | None, Field(description="The termination date.")] = None
    last_working_day: Annotated[date | None, Field(description="The last working day date.")] = None
    terminated_at: Annotated[
        date | None,
        Field(
            description="The date on which an employee submits their resignation or the employer issues a termination notice."
        ),
    ] = None
    type: Annotated[str | None, Field(description="The type of termination. Only listed values are valid.")] = None
    reason: Annotated[str | None, Field(description="The reason of the termination.")] = None


class FieldMetaLinks(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    href: str | None = None


class FieldMeta(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    links: Annotated[
        dict[str, FieldMetaLinks] | None,
        Field(examples=[{"links": {"self": {"href": "https://api.personio.de/v2/person?cursor=<current-cursor>"}}}]),
    ] = None


class Employment(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `employment`.")] = None
    position: EmploymentPosition | None = None
    status: Annotated[str | None, Field(description="The status of the employment. Only listed values are valid.")] = (
        None
    )
    weekly_working_hours: Annotated[float | None, Field(description="The total amount of weekly working hours.")] = None
    full_time_weekly_working_hours: Annotated[
        float | None, Field(description="The number of hours per week that is considered full time for the employment.")
    ] = None
    probation_end_date: Annotated[
        date | None, Field(description="The date that marks the end of the probation period.", examples=["2024-01-17"])
    ] = None
    employment_start_date: Annotated[
        date | None, Field(description="The date that marks the start of the employment.", examples=["2024-01-17"])
    ] = None
    employment_end_date: Annotated[
        date | None, Field(description="The date that marks the end of the employment.", examples=["2024-01-17"])
    ] = None
    type: Annotated[str | None, Field(description="The employment type. Only listed values are valid.")] = None
    contract_end_date: Annotated[
        date | None, Field(description="The date the contract ends for this employment.", examples=["2024-01-17"])
    ] = None
    created_at: Annotated[
        AwareDatetime | None, Field(description="The date and time this employment was created in Personio.")
    ] = None
    updated_at: Annotated[
        AwareDatetime | None, Field(description="The date and time this employment was last updated in Personio.")
    ] = None
    supervisor: EmploymentSupervisor | None = None
    office: EmploymentOffice | None = None
    org_units: Annotated[
        list[OrgUnit] | None,
        Field(description="All Org Units, i.e. department and team, directly associated with the employment."),
    ] = None
    person: EmploymentPerson | None = None
    termination: Termination | None = None
    cost_centers: Annotated[
        list[CostCenter] | None, Field(description="The list of cost centers this employment is attached to.")
    ] = None
    legal_entity: EmploymentLegalEntity | None = None
    job: Annotated[EmploymentJob | None, Field(description="The `job` associated with the employment.")] = None
    sub_company: Annotated[
        EmploymentSubCompany | None,
        Field(deprecated=True, description="This field is deprecated, use instead the legal entity."),
    ] = None
    field_meta: Annotated[FieldMeta | None, Field(alias="_meta")] = None
