# generated by datamodel-codegen:
#   filename:  persons-service-api-v2.json

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, JsonValue


class PersonProfilePicture(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    url: Annotated[str | None, Field(description="The URL of the person's profile picture")] = None


class PersonCustomAttribute(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for this `custom_attribute`.")] = None
    type: Annotated[
        str | None, Field(description="The type of the custom attribute. Only listed values are valid.")
    ] = None
    global_id: Annotated[
        str | None,
        Field(
            description="The global identifier for this attribute. This value is unique and can be set to a selected value at the creation of the custom attribute."
        ),
    ] = None
    label: Annotated[str | None, Field(description="The label defined for this attribute.")] = None
    value: JsonValue | None = None


class PersonEmploymentResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str | None = None


class FieldMetaLinks(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    href: str | None = None


class FieldMeta(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    links: Annotated[
        dict[str, FieldMetaLinks] | None,
        Field(examples=[{"links": {"self": {"href": "https://api.personio.de/v2/person?cursor=<current-cursor>"}}}]),
    ] = None


class Person(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: Annotated[str | None, Field(description="The unique identifier for the `Person`")] = None
    email: Annotated[
        str | None,
        Field(
            description="The email address this Person is connected with. The email is unique per Person, and the same Person can hold different Employments sharing the same email."
        ),
    ] = None
    created_at: Annotated[
        AwareDatetime | None, Field(description="The timestamp of when the person was created in UTC")
    ] = None
    updated_at: Annotated[
        AwareDatetime | None, Field(description="The timestamp of when the person was updated in UTC")
    ] = None
    first_name: Annotated[str | None, Field(description="The first name of the person")] = None
    last_name: Annotated[str | None, Field(description="The last name of the person")] = None
    preferred_name: Annotated[str | None, Field(description="The preferred name of the person")] = None
    gender: Annotated[str | None, Field(description="The gender of the person")] = None
    profile_picture: Annotated[PersonProfilePicture | None, Field(description="The person's profile picture")] = None
    status: Annotated[
        str | None,
        Field(
            description="The status of the person that is derived from the status of the latest person's employment. The person status will be set to ACTIVE if the current employment has ACTIVE, LEAVE or ONBOARDING status, otherwise the person status will be set to INACTIVE. Please use employment status to get more fine grained value for status."
        ),
    ] = None
    custom_attributes: list[PersonCustomAttribute] | None = None
    employments: list[PersonEmploymentResponse] | None = None
    field_meta: Annotated[FieldMeta | None, Field(alias="_meta")] = None
